---
title: "Google_Mobility_Sweden"
author: "Samar"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
#Time Series Plot Using ggplot

```{r,fig.width=16, fig.height=14}
library(datasets)
library(githubinstall)
library(tidyverse)
library(covdata)
library(ggforce)
library(dplyr)
library(timetk)
library(ggpubr)


```



#Google Mobility Data plot using ggplot

```{r,fig.width=16, fig.height=14}
p1<-google_mobility %>%
  filter(country_region_code == "SE", !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) %>%
  
  
  
  ggplot(mapping = aes(x = date, y = pct_diff,
                       group = sub_region_1,scales="free")) +
 
  
  geom_line(size = 0.5, color = "gray80") +
  geom_smooth(aes(color = type, group = 1), se = FALSE) +
  facet_wrap(~ type, ncol = 2) +
  labs(x = "Date", y = "Percent Change from Baseline", title = "Relative Trends in Mobility for Kinds of Location in the Sweden",
                              subtitle = "Data are relative to median activity between Jan and june",
       color = "Location Type",
       caption = "Data: Google. Graph: @kjhealy") +
  theme_minimal() +
  theme(legend.position = "top",
        strip.text = element_text(size = rel(1.3)))


p1<-p1 + facet_wrap(. ~ type, scales="free_y")

```
#USA

```{r,fig.width=16, fig.height=14}
p2<- google_mobility %>%
  filter(country_region_code == "US", !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) %>%
  
  
  
ggplot(mapping = aes(x = date, y = pct_diff,
                       group = sub_region_1,scales="free")) +
 
  
  geom_line(size = 0.5, color = "gray80") +
  geom_smooth(aes(color = type, group = 1), se = FALSE) +
  facet_wrap(~ type, ncol = 2) +
  labs(x = "Date", y = "Percent Change from Baseline", title = "Relative Trends in Mobility for Kinds of Location in the USA",
                              subtitle = "Data are relative to median activity between Jan and june",
       color = "Location Type",
       caption = "Data: Google. Graph: @kjhealy") +
  theme_minimal() +
  theme(legend.position = "top",
        strip.text = element_text(size = rel(1.3)))
p2<-p2 + facet_wrap(. ~ type, scales="free_y")

```
#Neighbouring nations to sweden(finland,norway)

```{r,fig.width=16, fig.height=14}
p3<-google_mobility %>%
  filter(country_region_code %in% c("FI", "NO"), !is.na(sub_region_1), is.na(sub_region_2)) %>%
  mutate(type = tools::toTitleCase(type)) %>%
  
  
  
  ggplot(mapping = aes(x = date, y = pct_diff,
                       group = sub_region_1,scales="free")) +
 
  
  geom_line(size = 0.5, color = "gray80") +
  geom_smooth(aes(color = type, group = 1), se = FALSE) +
  facet_wrap(~ type, ncol = 2) +
  labs(x = "Date", y = "Percent Change from Baseline", title = "Relative Trends in Mobility for Kinds of Location in the norway and finland",
                              subtitle = "Data are relative to median activity between Jan and june",
       color = "Location Type",
       caption = "Data: Google. Graph: @kjhealy") +
  theme_minimal() +
  theme(legend.position = "top",
        strip.text = element_text(size = rel(1.3)))

p3<-p3 + facet_wrap(. ~ type, scales="free_y")

#Combining

figure <- ggarrange(p1, p2, p3,
                    labels = c("A", "B", "C"),
                    ncol = 2, nrow = 2)


figure 


```


#Reference

```{r}

# -------
 # Article title = Mobility Data from Apple and Google,
  #author = Kieran Healy,
  #year = 2020,
  #note = R package version 0.1.0,
  #url = https://kjhealy.github.io/covdata/articles/mobility-data.html

#--------------

```

```

